# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###Get ALL Data from Table
GET http://localhost:8080/all
Content-Type: application/json

###Create a Short URL
POST http://localhost:8080/minify
Content-Type: application/json

{
  "longURL": "https://mail.google.com",
  "userId": "12321"
}

###Get All users
GET http://localhost:8080/users/all
Content-Type: application/json

###Create User
POST http://localhost:8080/users/create
Content-Type: application/json

{
  "firstName": "Sachin",
  "lastName": "Singh",
  "email": "ss@gmail.com"
}

###