title: Coding Interview Preparation
description: A collection of resources for coding interview preparation, focusing on data structures and algorithms with Java solutions.
theme: jekyll-theme-cayman
